[build.environment]
  FFMPEG_PATH = "/opt/build/repo/ffmpeg"
  FFPROBE_PATH = "/opt/build/repo/ffprobe"

[context.production]
  command = """
  wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
  tar xvf ffmpeg-git-amd64-static.tar.xz
  mv **/ffmpeg **/ffprobe /opt/build/repo
  ls -lah
  ls -lah /opt/build/repo
  """

[functions]
  directory = "/functions"
  included_files = ["README.md"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/netlify"
  status = 200
  force = true

[[headers]]
  for = "/"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "*"
  Access-Control-Allow-Methods = "*"
